export enum DefaultKeys
{
  start     = 'enter',
  select    = 'space',
  l         = 'e',
  l2        = 'r',
  r         = 'p',
  r2        = 'o',
  a         = 'h',
  b         = 'g',
  x         = 'y',
  y         = 't',
  up        = 'up',
  left      = 'left',
  down      = 'down',
  right     = 'right',
  l_x_minus = 'a',
  l_x_plus  = 'd',
  l_y_minus = 'w',
  l_y_plus  = 's',
  l3_btn    = 'x',
  r_x_minus = 'j',
  r_x_plus  = 'l',
  r_y_minus = 'i',
  r_y_plus  = 'k',
  r3_btn    = 'comma',
}